parameters:
    elysion.qualitelis.denormalizers.prestaire: 'Elysion\QualitelisConnectorBundle\Denormalizer\PrestataireDenormalizer'
    elysion.qualitelis.denormalizers.all_prestaires: 'Elysion\QualitelisConnectorBundle\Denormalizer\AllPrestatairesDenormalizer'

services:
    # Denormalizers
    elysion.qualitelis.denormalizer.prestataire:
        class: "%elysion.qualitelis.denormalizers.prestaire%"
        arguments:
            - "%elysion.qualitelis.model.prestataire%"
            - "%elysion.qualitelis.model.comment%"

    elysion.qualitelis.denormalizer.all_prestataires:
        class: "%elysion.qualitelis.denormalizers.all_prestaires%"
        arguments:
            - "%elysion.qualitelis.model.prestataire%"
            - "%elysion.qualitelis.model.comment%"
